apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong-app
          image: pingpong-app:latest  
          volumeMounts:
            - name: ping-logoutput-volume
              mountPath: /usr/src/app/files/
      volumes:
        - name: ping-logoutput-volume
          persistentVolumeClaim:
            claimName: ping-logoutput-claim
