apiVersion: batch/v1
kind: CronJob
metadata:
  name: read-wiki-reminder
  namespace: todo-ns
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: read-wiki
            image: postgres:12.3-alpine
            imagePullPolicy: Never
            env:
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: db
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: user
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: db-port
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SECRET
            command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache curl postgresql-client
              LOCATION=$(curl -s -I "https://en.wikipedia.org/wiki/Special:Random" | grep -i "location:" | awk '{print $2}' | tr -d '\r')
              echo $LOCATION
              # check fetched location
              if [ -z "$LOCATION" ]; then
                echo "Failed to fetch Location header from Wikipedia."
                exit 1
              fi

              # Use the Location URL as the task
              task=" read $LOCATION"

              # Insert the task into the todos table
              psql "postgresql://$USER:$POSTGRES_PASSWORD@$HOST/$DB" <<EOF
                INSERT INTO todos (task) VALUES ('$task');
              EOF

              # Check if the psql command succeeded
              if [ $? -eq 0 ]; then
                echo "Task inserted successfully: $task"
              else
                echo "Failed to insert task into the database."
                exit 1
              fi
          restartPolicy: Never