apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: todo-app:latest
          volumeMounts:
            - name: image-volume
              mountPath: /usr/src/app/images
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: port
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: db
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: user
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: db-port
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SECRET 