apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: todo-ns
  name: image-pv
spec:
  storageClassName: local-image-pv 
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube/images
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0