apiVersion: v1
kind: Service
metadata:
  namespace: todo-ns
  name: todo-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: todo-ns
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: postgres-db