apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
  namespace: log-pingpong-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput-app
  template:
    metadata:
      labels:
        app: logoutput-app
    spec:
      volumes:
        - name: logoutput-volume
          persistentVolumeClaim:
            claimName: logoutput-claim
      containers:
        - name: logoutput-writer-container
          image: logoutput-writer:latest
          volumeMounts:
            - name: logoutput-volume
              mountPath: /usr/src/app/files
        - name: logoutput-reader-container
          image: logoutput-reader:latest
          volumeMounts:
            - name: logoutput-volume
              mountPath: /usr/src/app/files
        - name: pingpong-container
          image: pingpong-app:latest
          env:
            - name: FILE_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: pingpong-configmap
                  key: information.txt
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: pingpong-configmap
                  key: message
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SECRET 
          # volumeMounts:
          #   - name: logoutput-volume
          #     mountPath: /usr/src/app/files
