apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logoutput-claim
  namespace: log-pingpong-ns
spec:
  storageClassName: local-logoutput-pv 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi