apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      # volumes: # Define volume
      #   - name: shared-logs
      #     persistentVolumeClaim:
      #       claimName: image-claim
      containers:
        - name: log-output
          image: log-output
          env:
           - name: MESSAGE
             valueFrom:
              configMapKeyRef:
               name: log-output-configmap
               key: message
          volumeMounts:
          - name: log-output-config
            mountPath: "/config"
            readOnly: true
      volumes:
      - name: log-output-config
        configMap:
         name: log-output-configmap
         items:
         - key: "information.txt"
           path: "information.txt"
  
          
       
          # volumeMounts: # Mount volume
          # - name: shared-logs
          #   mountPath: /usr/src/app/files
        # - name: logs-file
        #   image: logs-file
          # volumeMounts: # Mount volume
          # - name: shared-logs
          #   mountPath: /usr/src/app/files