apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-app
        - name: ping-pong
          image: ping-pong
          command: ["sh", "-c", "ulimit -n 65536 && npm start"]
          env:
          - name: PORT
            value: "3000"